"""Tests for claude_context.parsers.transcript using handwritten synthetic records."""

from __future__ import annotations

import json
from pathlib import Path

from claude_context.models import (
    ROLE_ASSISTANT,
    ROLE_SUMMARY,
    ROLE_TOOL_CALL,
    ROLE_TOOL_RESULT,
    ROLE_USER,
    TOOL_RESULT_INDEX_CHARS,
)
from claude_context.parsers.transcript import (
    IGNORED_TYPES,
    load_subagent_meta,
    parse_chunk,
    parse_line_full,
    render_tool_call,
)

SESSION = "00000000-0000-4000-8000-000000000001"
THINKING_SENTINEL = "PRIVATE-THOUGHT-SENTINEL-7f3a"
FAKE_SECRET = "sk-" + "proj-" + "AbCdEfGhIjKlMnOp1234567890qrstuv"


def rec(type_: str, n: int = 0, **fields: object) -> dict:
    base = {
        "type": type_,
        "uuid": f"uuid-{type_}-{n}",
        "parentUuid": None,
        "timestamp": f"2026-01-02T03:04:{n:02d}.000Z",
        "sessionId": SESSION,
        "cwd": "/home/user/project",
        "gitBranch": "main",
        "version": "2.0.0",
        "entrypoint": "cli",
        "isSidechain": False,
    }
    base.update(fields)
    return base


def user(content: object, n: int = 0, **fields: object) -> dict:
    return rec("user", n, message={"role": "user", "content": content}, **fields)


def assistant(blocks: list, n: int = 0, **fields: object) -> dict:
    return rec("assistant", n, message={"role": "assistant", "content": blocks}, **fields)


def jsonl(*records: object) -> bytes:
    return b"".join(json.dumps(r).encode() + b"\n" for r in records)


def parse(*records: object):
    return parse_chunk(jsonl(*records))


def texts(chunk) -> list[str]:
    return [m.text for m in chunk.messages]


# --- user content -------------------------------------------------------------------------


def test_string_and_list_content_prompts() -> None:
    chunk = parse(
        user("fix the failing test", 1),
        user([{"type": "text", "text": "first"}, {"type": "text", "text": "second"}], 2),
    )
    assert [(m.role, m.text, m.is_prompt) for m in chunk.messages] == [
        (ROLE_USER, "fix the failing test", True),
        (ROLE_USER, "first\n\nsecond", True),
    ]
    m = chunk.messages[0]
    assert m.uuid == "uuid-user-1"
    assert m.ts == "2026-01-02T03:04:01.000Z"
    assert m.text_len == len(m.text)


def test_images_and_documents_appended_to_prompt() -> None:
    chunk = parse(
        user(
            [
                {"type": "text", "text": "what is in this?"},
                {"type": "image", "source": {"type": "base64", "data": "AAAA"}},
                {"type": "document", "source": {"type": "base64", "data": "BBBB"}, "title": "x.pdf"},
            ]
        )
    )
    assert texts(chunk) == ["what is in this?\n\n[image]\n\n[document]"]
    assert chunk.messages[0].is_prompt


def test_image_only_is_not_a_typed_prompt() -> None:
    chunk = parse(user([{"type": "image", "source": {}}]))
    assert texts(chunk) == ["[image]"]
    assert not chunk.messages[0].is_prompt


def test_is_meta_skipped() -> None:
    chunk = parse(user("<system-reminder>injected</system-reminder>", isMeta=True))
    assert chunk.messages == []


def test_harness_tags_stripped() -> None:
    raw = (
        "<system-reminder>\nremember things\n</system-reminder>\n"
        "<local-command-caveat>Caveat: generated by commands</local-command-caveat>\n"
        "<ide_opened_file>The user opened /home/user/a.py</ide_opened_file>\n"
        "please refactor this"
    )
    chunk = parse(user(raw))
    assert texts(chunk) == ["please refactor this"]
    assert chunk.messages[0].is_prompt


def test_only_injected_content_emits_nothing() -> None:
    chunk = parse(user("<system-reminder>a</system-reminder>\n  \n<ide_selection>b</ide_selection>"))
    assert chunk.messages == []


def test_task_notification_is_not_a_prompt() -> None:
    raw = "<task-notification><task-id>t1</task-id><summary>done</summary></task-notification>"
    assert parse(user(raw)).messages == []
    chunk = parse(user(raw + "\nthanks, continue", origin={"kind": "task-notification"}))
    assert texts(chunk) == ["thanks, continue"]
    assert not chunk.messages[0].is_prompt


def test_slash_command_rendered_as_prompt() -> None:
    raw = (
        "<command-message>review is running…</command-message>\n"
        "<command-name>/review</command-name>\n"
        "<command-args>src/app.py --strict</command-args>"
    )
    chunk = parse(user(raw))
    assert texts(chunk) == ["/review src/app.py --strict"]
    assert chunk.messages[0].is_prompt
    empty_args = "<command-name>/clear</command-name><command-message>clear</command-message><command-args></command-args>"
    assert texts(parse(user(empty_args))) == ["/clear"]


def test_local_command_stdout_is_text_but_not_prompt() -> None:
    chunk = parse(user("<local-command-stdout>Set model to default</local-command-stdout>"))
    assert texts(chunk) == ["Set model to default"]
    assert not chunk.messages[0].is_prompt


def test_bash_mode_input_and_output() -> None:
    chunk = parse(
        user("<bash-input>ls -la</bash-input>", 1),
        user("<bash-stdout>file.txt</bash-stdout><bash-stderr></bash-stderr>", 2),
    )
    assert [(m.text, m.is_prompt) for m in chunk.messages] == [("! ls -la", True), ("file.txt", False)]


def test_pasted_content_wrapper_unwrapped() -> None:
    raw = '<pasted_content id="p1">line one\nline two</pasted_content id="p1">\nsummarize the above'
    assert texts(parse(user(raw))) == ["line one\nline two\nsummarize the above"]


def test_interrupt_marker_is_not_a_prompt() -> None:
    chunk = parse(user([{"type": "text", "text": "[Request interrupted by user for tool use]"}]))
    assert texts(chunk) == ["[Request interrupted by user for tool use]"]
    assert not chunk.messages[0].is_prompt


def test_sidechain_user_text_is_not_a_prompt() -> None:
    chunk = parse(user("Search the codebase for X", isSidechain=True, agentId="a0123456789abcdef"))
    assert texts(chunk) == ["Search the codebase for X"]
    assert not chunk.messages[0].is_prompt


# --- tool calls and results ---------------------------------------------------------------


def test_tool_use_and_tool_results() -> None:
    chunk = parse(
        assistant(
            [
                {"type": "text", "text": "Let me look."},
                {"type": "tool_use", "id": "toolu_A", "name": "Read", "input": {"file_path": "/home/user/a.py"}},
                {"type": "tool_use", "id": "toolu_B", "name": "Bash", "input": {"command": "false"}},
            ],
            1,
        ),
        user(
            [
                {"type": "tool_result", "tool_use_id": "toolu_A", "content": "print('hi')"},
                {
                    "type": "tool_result",
                    "tool_use_id": "toolu_B",
                    "is_error": True,
                    "content": [
                        {"type": "text", "text": "exit 1"},
                        {"type": "image", "source": {}},
                        {"type": "tool_reference", "tool_name": "WebSearch"},
                        {"type": "mystery"},
                    ],
                },
            ],
            2,
        ),
    )
    roles = [(m.role, m.block_index) for m in chunk.messages]
    assert roles == [
        (ROLE_ASSISTANT, 0),
        (ROLE_TOOL_CALL, 1),
        (ROLE_TOOL_CALL, 2),
        (ROLE_TOOL_RESULT, 0),
        (ROLE_TOOL_RESULT, 1),
    ]
    read, bash = chunk.messages[1], chunk.messages[2]
    assert (read.tool_name, read.tool_use_id, read.text) == ("Read", "toolu_A", "Read: /home/user/a.py")
    assert bash.text == "Bash: false"
    ok, err = chunk.messages[3], chunk.messages[4]
    assert (ok.tool_use_id, ok.text, ok.is_error) == ("toolu_A", "print('hi')", False)
    assert err.is_error
    assert err.text == "exit 1\n[image]\n[tool_reference: WebSearch]"
    assert not any(m.is_prompt for m in chunk.messages)


def test_tool_result_truncated_in_chunk_but_not_in_full_parse() -> None:
    body = "line of output\n" * 1000
    record = user([{"type": "tool_result", "tool_use_id": "toolu_X", "content": body}])
    m = parse(record).messages[0]
    assert len(m.text) == TOOL_RESULT_INDEX_CHARS
    assert m.text_len == len(body)
    full = parse_line_full(json.dumps(record).encode())
    assert full[0].text == body
    assert full[0].text_len == len(body)


def test_render_tool_call() -> None:
    assert render_tool_call("Bash", {"command": "ls", "description": "List files"}) == "Bash: List files"
    assert render_tool_call("Bash", {"command": "echo " + "a" * 500}) == "Bash: echo " + "a" * 195
    assert render_tool_call("Edit", {"file_path": "/home/user/x.py", "old_string": "a"}) == "Edit: /home/user/x.py"
    assert render_tool_call("NotebookEdit", {"notebook_path": "/home/user/n.ipynb"}) == "NotebookEdit: /home/user/n.ipynb"
    assert render_tool_call("Grep", {"pattern": "def main", "path": "/home/user/src"}) == "Grep: def main in /home/user/src"
    assert render_tool_call("Glob", {"pattern": "**/*.py"}) == "Glob: **/*.py"
    assert render_tool_call("WebFetch", {"url": "https://example.com/doc"}) == "WebFetch: https://example.com/doc"
    assert render_tool_call("WebSearch", {"query": "python regex"}) == "WebSearch: python regex"
    assert render_tool_call("Agent", {"description": "Find callers", "prompt": "long"}) == "Agent: Find callers"
    assert render_tool_call("Task", {"description": "Find callers"}) == "Task: Find callers"
    assert render_tool_call("Skill", {"skill": "review", "args": "--fast"}) == "Skill: review --fast"
    assert render_tool_call("mcp__notes__search", {"q": "a\nb"}) == 'mcp__notes__search: {"q":"a\\nb"}'
    assert render_tool_call("Bash", {"command": "line1\n  line2", "description": ""}) == "Bash: line1 line2"
    assert render_tool_call("Read", None) == "Read"
    assert render_tool_call("Other", "not-a-dict") == 'Other: "not-a-dict"'


def test_render_tool_call_redacts_before_truncating() -> None:
    cmd = "x" * 190 + f" K={FAKE_SECRET}"
    out = render_tool_call("Bash", {"command": cmd})
    assert "sk-proj" not in out
    assert "AbCdEf" not in out


# --- thinking, secrets, skipped records ---------------------------------------------------


def test_thinking_never_appears() -> None:
    record = assistant(
        [
            {"type": "thinking", "thinking": THINKING_SENTINEL, "signature": THINKING_SENTINEL},
            {"type": "redacted_thinking", "data": THINKING_SENTINEL},
            {"type": "text", "text": "answer"},
        ]
    )
    chunk = parse(record)
    full = parse_line_full(json.dumps(record).encode())
    dumped = repr(chunk) + repr(full)
    assert THINKING_SENTINEL not in dumped
    assert texts(chunk) == ["answer"]
    assert chunk.messages[0].block_index == 2


def test_api_error_records_skipped() -> None:
    chunk = parse(assistant([{"type": "text", "text": "API Error: overloaded"}], isApiErrorMessage=True))
    assert chunk.messages == []


def test_secrets_redacted_in_prompt_and_tool_output() -> None:
    chunk = parse(
        user(f"use this key {FAKE_SECRET} please", 1),
        user([{"type": "tool_result", "tool_use_id": "t", "content": "DB_PASSWORD=hunter22\nok"}], 2),
        assistant([{"type": "tool_use", "id": "t2", "name": "Bash", "input": {"command": f"export K={FAKE_SECRET}"}}], 3),
    )
    blob = "\n".join(texts(chunk))
    assert FAKE_SECRET not in blob and "hunter22" not in blob
    assert "[REDACTED:openai_key]" in chunk.messages[0].text
    assert chunk.messages[1].text == "DB_PASSWORD=[REDACTED:password]\nok"


# --- chunking ------------------------------------------------------------------------------


def test_partial_trailing_line_and_resume() -> None:
    data = jsonl(user("one", 1), user("two", 2), user("three", 3))
    first_two = len(jsonl(user("one", 1), user("two", 2)))
    cut = first_two + 10  # mid-way through the third line

    a = parse_chunk(data[:cut], base_offset=0)
    assert a.consumed == first_two
    assert texts(a) == ["one", "two"]
    assert [m.line_offset for m in a.messages] == [0, len(jsonl(user("one", 1)))]

    b = parse_chunk(data[a.consumed :], base_offset=a.consumed)
    assert b.consumed == len(data) - a.consumed
    assert texts(b) == ["three"]
    assert b.messages[0].line_offset == first_two
    assert data[b.messages[0].line_offset :].startswith(b'{"type": "user"')


def test_no_complete_line_consumes_nothing() -> None:
    chunk = parse_chunk(b'{"type": "user", "mess', base_offset=100)
    assert chunk.consumed == 0 and chunk.messages == []


def test_malformed_and_odd_lines() -> None:
    data = (
        jsonl(user("before", 1))
        + b"{not json\n"
        + b'"a bare string"\n'
        + b"[1, 2]\n"
        + b"\n"
        + b'{"type": "user", "message": {"content": "caf\xff\xfe"}}\n'
        + jsonl(
            {"type": "user"},
            {"type": "user", "message": "not a dict"},
            {"type": "user", "message": {"content": 42}},
            {"type": "assistant", "message": {"content": None}},
            {"type": "assistant", "message": {"content": [None, 3, {"type": "text", "text": 5}]}},
            {"no_type": True},
            user("after", 2),
        )
    )
    chunk = parse_chunk(data)
    assert chunk.consumed == len(data)
    assert chunk.malformed_lines == 3
    assert texts(chunk) == ["before", "caf��", "after"]
    assert chunk.unknown_types == {"<missing>": 1}


# --- facts and record types ----------------------------------------------------------------


def test_session_facts() -> None:
    chunk = parse(
        user("hi", 5),
        rec("attachment", 9, cwd="/home/user/other", gitBranch="feature", version="2.1.0"),
        assistant([{"type": "text", "text": "hello"}], 2, entrypoint="sdk-cli"),
    )
    f = chunk.facts
    assert f.session_id == SESSION
    assert f.agent_id is None
    assert (f.cwd, f.git_branch, f.cc_version) == ("/home/user/project", "main", "2.0.0")
    assert f.entrypoint == "sdk-cli"
    # attachment timestamps do not count toward first/last
    assert (f.first_ts, f.last_ts) == ("2026-01-02T03:04:02.000Z", "2026-01-02T03:04:05.000Z")


def test_ai_title_latest_wins() -> None:
    chunk = parse(
        {"type": "ai-title", "sessionId": SESSION, "aiTitle": "First title"},
        {"type": "ai-title", "sessionId": SESSION, "aiTitle": "Better title"},
    )
    assert chunk.facts.title == "Better title"
    assert chunk.messages == []


def test_compaction_summary() -> None:
    summary = f"Summary of the conversation so far. Key was {FAKE_SECRET}."
    chunk = parse(
        {"type": "summary", "summary": "old-style summary", "leafUuid": "x"},
        user(summary, 1, isCompactSummary=True, isVisibleInTranscriptOnly=True),
        {"type": "summary", "summary": "later old-style summary", "leafUuid": "y"},
    )
    assert len(chunk.messages) == 1
    m = chunk.messages[0]
    assert m.role == ROLE_SUMMARY and not m.is_prompt
    assert FAKE_SECRET not in m.text and "[REDACTED:openai_key]" in m.text
    assert chunk.facts.summary == m.text


def test_old_style_summary_used_without_compaction() -> None:
    chunk = parse({"type": "summary", "summary": "Fixed the login bug", "leafUuid": "x"})
    assert chunk.facts.summary == "Fixed the login bug"


def test_unknown_types_counted_ignorable_not() -> None:
    records = [{"type": t, "sessionId": SESSION} for t in sorted(IGNORED_TYPES)]
    records += [{"type": "brand-new-type"}, {"type": "brand-new-type"}, {"type": "other-new"}]
    chunk = parse(*records)
    assert chunk.unknown_types == {"brand-new-type": 2, "other-new": 1}
    assert chunk.messages == []


def test_subagent_facts_and_meta(tmp_path: Path) -> None:
    agent = "a0123456789abcdef"
    chunk = parse(
        user("Investigate the parser", 1, isSidechain=True, agentId=agent),
        assistant([{"type": "text", "text": "Done."}], 2, isSidechain=True, agentId=agent),
    )
    assert chunk.facts.agent_id == agent
    assert chunk.facts.session_id == SESSION

    meta = tmp_path / f"agent-{agent}.meta.json"
    meta.write_text(json.dumps({"agentType": "Explore", "description": "Investigate the parser"}))
    assert load_subagent_meta(meta) == {"agentType": "Explore", "description": "Investigate the parser"}
    (tmp_path / "bad.json").write_text("{nope")
    (tmp_path / "list.json").write_text("[1]")
    assert load_subagent_meta(tmp_path / "bad.json") == {}
    assert load_subagent_meta(tmp_path / "list.json") == {}
    assert load_subagent_meta(tmp_path / "missing.json") == {}


def test_parse_line_full_matches_chunk_addressing() -> None:
    record = assistant(
        [
            {"type": "thinking", "thinking": "x", "signature": "y"},
            {"type": "tool_use", "id": "toolu_Q", "name": "Glob", "input": {"pattern": "*.md"}},
        ]
    )
    chunk_msgs = parse(record).messages
    full = parse_line_full(json.dumps(record).encode() + b"\n")
    assert [(m.role, m.block_index, m.text) for m in full] == [
        (m.role, m.block_index, m.text) for m in chunk_msgs
    ]
    assert parse_line_full(b"garbage") == []
